### ISSUE TITLE
Docs Request

### ISSUE THREAD

**Issue by khaije1** [amendlik/gitstack-pillar#1]
Questions

1. Is Gitstack a fork from https://github.com/bbinet/pillarstack or a rewrite? If so, is it intended to exist separately or be merged back in to Pillarstack?
3. Are you interested in maintaining feature parity with pillarstack? In particular the Jinja environment features of Salt, (and consequently pillarstack), are always expanding, are you interested in supporting up to date Jinja in GitStack?
4. Any particular advice for people interested in switching from pillarstack to GitStack?
5. Are you interested in feeding gitstack into Salt so that it can be available by default in a future release?
6. Is GitStack intended as a cut-over replacement for Pillarstack or more of a redesign replacement?
7. Any other interesting plans for the future for this module?

I ask as someone who is interested in switching from Pillarstack to GitStack.
 - https://github.com/bbinet/pillarstack/issues/16
 - https://github.com/bbinet/pillarstack/issues/24

**Comment by amendlik** [comment]
I think you'll find most of these questions answered in the [readme](https://github.com/amendlik/gitstack-pillar/blob/master/README.md), particularly the [Internals](https://github.com/amendlik/gitstack-pillar#internals) section. I will address them briefly here.

1. All GitStack does is handle the pluming to fetch the Git repository, then pass the request to PillarStack. GitStack depends 100% on PillarStack and does not reproduce any of its functionality.
2. GitStack supports whatever PillarStack supports.
3. It's really as simple as putting your PillarStack code in a Git repository and slightly modifying your config files (for both Salt and PillarStack). This is all explained in the readme.
4. This is written to be a plugin. As such, it is limited to the capabilities of a plugin. If I was going to put this in the SaltStack code, I would handle some things differently, such as the dependency on the Git Pillar. That said, SaltStack are welcome to use this code as they wish.
5. See previous answers.
6. Not really. This plugin doesn't actually do anything but glue together Salt's internal Git polling and the PillarStack Pillar. Any new features should be added to PillarStack.

Thank you for your interest.

**Comment by khaije1** [comment]
Thanks the explanation! I'm now happily using GitStack with Pillarstack.
