### ISSUE TITLE
Sync with Saltstack repo

### ISSUE THREAD

**Issue by Angelo-Verona** [amendlik/gitstack-pillar#5]
Will you do pull request for saltstack repository for gitstack.py? It's quite handy.

**Comment by amendlik** [comment]
I'm glad you're getting some value out of it!

The question of incorporating this into Salt is an interesting one. The whole project is basically a "hack" that takes advantage of the fact that Salt contains code for fetching Git fileserver backends. If I was going to build this into Salt, I would take a very different approach to that challenge.

In any case, I've been speaking to them lately about promoting community-created integrations. I'll see if they have any interest in including this project in the product.
